### ISSUE TITLE
my challenges using the library

### ISSUE THREAD

**Issue by emmanuelthesis** [fentec-project/CiFEr#22] opened 2020-05-15 13:00 UTC
I want to use the library to implement an access control using ABE. The process involves communication between two parties. I initiated the cpabe-setup at the receiver end and send the public key through a safe channel to the sender of the message. After receiving the public key and perform the encryption of the message with some sets of access structure and the public key, i sent the resulting ciphertext to the receiver but the decryption never possible, i get segmentation (core dumped) always. what could be the possible problems and how can i correct it?

**Comment by tilenmarc** [comment] 2020-05-15 14:27
Hi Emmanuel,
what you describe seems correct. It might be some problem when you change structs into something you can send and then change back. But it is hard to say, I am just guessing. Do you have the code in some public repository so I can have a look?

**Comment by emmanuelthesis** [comment] 2020-05-15 14:41
no, but i can share the part of the code that is not working with you.

    FP12_BN254 msg;
    FP12_BN254_one(&msg);

    char bool_exp[] = "(5 OR 3) AND ((2 OR 4) OR (1 AND 6))";
    size_t bool_exp_len = strlen(bool_exp);
    cfe_msp msp;
    cfe_error error;
    error = cfe_boolean_to_msp(&msp, bool_exp, bool_exp_len, false);
    printf("The cfe_boolean_to_msp error : %d\n", error);
 
    cfe_fame_cipher cipher;
    cfe_fame_cipher_init(&cipher, &msp);
    cfe_fame_encrypt(&cipher, &msg, &msp, (cfe_fame_pub_key *)rec_pk->data, &fame);
    np_send(ac, "sendmessage", (const unsigned char *)&cipher, sizeof(cfe_fame_cipher));
     the rec_pk is the public key received.
  
the cipher was published for decryption,
at the receiver, 
FP12_BN254 decryption;
cfe_fame_decrypt(&decryption, (cfe_fame_cipher *)msg_cipher->data, &keys, &fame);
msg_cipher refers to the cipher

**Comment by tilenmarc** [comment] 2020-05-15 15:20
I think the problem is that you send the cipher as `(const unsigned char *)&cipher` while the struct `cfe_fame_cipher` also includes some arrays (pointers) so when you change it to a string, only pointers get sent, while data does not.
I accept that designing struct `cfe_cipher` did not anticipate this problem, so I will look into how to fix this in the next week. You can expect some general solution soon.

**Comment by emmanuelthesis** [comment] 2020-05-15 15:28
oh okay. Thanks for your timely reply. i look forward to your feedback.

**Comment by emmanuelthesis** [comment] 2020-05-25 09:48
Hi,
Please i have been waiting for the update. just a reminder. Thanks

**Comment by tilenmarc** [comment] 2020-05-25 10:03
Hi Emmanuel,
we are working on it. Like I said your problem is that you are changing a struct cipher into a string by just calling `(const unsigned char *)&cipher`. This is not ok. We are now working on writing a general solution for this by defining functions that change each struct into string and vice versa. This is not as simple as it sounds in C. We are currently testing [this library](https://github.com/protobuf-c/protobuf-c) to see if it works ok with our structures.
If you are in a hurry, you can try to do it for FAME scheme manually. Nevertheless, as soon as I have something that works for FAME, I will let you know (hopefully til the end of this week).

**Comment by emmanuelthesis** [comment] 2020-05-25 10:11
Thanks for your usual timely reply. I will wait till the end of the week. i understand it's not easy.

**Comment by tilenmarc** [comment] 2020-06-01 07:34
Just to let you know, I am finishing the implementation of the serialization of structs and should be finished for the FAME scheme today. Will let you know.

**Comment by emmanuelthesis** [comment] 2020-06-01 09:25
Great. Thanks for the update.

**Comment by tilenmarc** [comment] 2020-06-01 14:41
Hi Emmanuel,
if you want to use newly implemented functions please get this fork of the implementation in the branch "marshalling": [https://github.com/tilenmarc/CiFEr/tree/marshalling](https://github.com/tilenmarc/CiFEr/tree/marshalling)
Since this needs to be reviewed and other thing will be added, it is not yet merged in master CiFEr.
To work you will need to install two libraries:
- [protobuf](https://github.com/protocolbuffers/protobuf) C++ version
- [protobuf-c](https://github.com/protobuf-c/protobuf-c)
These are libraries for changing structs to string.
I implemented in CiFEr functions like `cfe_fame_cipher_ser` and `cfe_fame_cipher_read`. That will change `cfe_fame_cipher` into struct `cfe_ser`. `cfe_ser` is composed of two things: .ser gives you an array of bytes that you can send and ,len gives you the length of this array.
See in `test/serialization/fame_ser.c` an example of how to use it.
Please let me know if it works for you.

**Comment by emmanuelthesis** [comment] 2020-06-01 15:26
Thanks for the positive update. I will do the implementation and get back to you.

**Comment by emmanuelthesis** [comment] 2020-06-02 20:11
i modified the code as follows:
FP12_BN254 msg;
    FP12_BN254_one(&msg);

    char bool_exp[] = "(5 OR 3) AND ((2 OR 4) OR (1 AND 6))";
    size_t bool_exp_len = strlen(bool_exp);
    cfe_msp msp;
    cfe_error error;
    error = cfe_boolean_to_msp(&msp, bool_exp, bool_exp_len, false);
    printf("The cfe_boolean_to_msp error : %d\n", error);
 
    cfe_ser buf;
    cfe_fame_pub_key pk;
    cfe_fame_pub_key_read(&pk, (cfe_ser *)rec_pk->data);
    cfe_fame_cipher cipher;
    cfe_fame_cipher_init(&cipher, &msp);
    cfe_fame_encrypt(&cipher, &msg, &msp, &pk, &fame);
    cfe_fame_cipher_ser(&cipher, &buf);
    np_send(ac, "sendmessage", (const unsigned char *)&buf, sizeof(buf));

and at the receiver ends:
    cfe_fame_cipher cipher2;
    cfe_fame_cipher_read(&cipher2, (cfe_ser *)msg_cipher->data);
    error = cfe_fame_decrypt(&decryption, &cipher2, &keys, &fame); 

but not working, maybe i am still getting something wrong.

**Comment by tilenmarc** [comment] 2020-06-03 07:43
Hi,
you are again sending a struct instead of a string. Like I wrote, `cfe_ser` is composed of two things: .ser gives you an array of bytes that you can send and .len gives you the length of this array. So don't send `(const unsigned char *)&buf` but `(const unsigned char *) buf.ser`, with length `buf.len`.
So it should be something like:
`cfe_ser buf;
cfe_fame_cipher cipher;
cfe_fame_cipher_init(&cipher, &msp);
cfe_fame_encrypt(&cipher, &msg, &msp, &pk, &fame);
cfe_fame_cipher_ser(&cipher, &buf);
np_send(ac, "sendmessage", (const unsigned char *)buf.ser, buf.len);`
On the receiver end you should have something like:
`cfe_fame_cipher cipher2;
cfe_ser buf2;
buf2.ser = (int8_t *)msg_cipher->data;
buf2.len = ?? define length of received data, I am not familiar with functions that you are using ??;
cfe_fame_cipher_read(&cipher2, &buf2);`
Use the same procedure to also send the public key. Also note that in the code we are changing between `int8_t` and `unsigned char`, which should be both of the same size (1 byte) on usual platforms, but could also not be, so you might need to take care of this.

**Comment by emmanuelthesis** [comment] 2020-06-03 09:00
Thanks for the correction. making the necessary corrections, i will get back to you.

**Comment by emmanuelthesis** [comment] 2020-06-03 09:05
Thanks. it works fine. Thanks for your support. you are the best.

**Comment by tilenmarc** [comment] 2020-06-03 09:43
Great! No problem.

**Comment by emmanuelthesis** [comment] 2020-06-03 11:31
I found out about a msgpack for serialization and de-serialization.  Just a feedback or recommendation for a serialization and de-serialization. Maybe in might be useful for you.

**Comment by ThibsG** [comment] 2020-12-10 07:52
hello @tilenmarc , first of all thanks for all your work on this library.

I'm trying to extend your work on serialization for GPSW as well.
For example to serialize the GPSW public key which has the following structure:
```c
typedef struct cfe_gpsw_pub_key {
    cfe_vec_G2 t;
    FP12_BN254 y;
} cfe_gpsw_pub_key;
```
 I have defined in `include/cifer/serialization/data.proto`:
```protobuf
message cfe_vec_g2_ser {
        repeated octet_ser vec = 1;
        required int64 size = 2;
}

message cfe_gpsw_pub_key_ser {
        required cfe_vec_g2_ser t = 1;
        required octet_ser y = 2;
}
```
and re-generated code using: `protoc --c_out=. data.proto`
Serializing `FP12_BN254 y` seems not to be a problem with `octet_ser`, but I struggle with `cfe_vec_G2 t`. I can't even create and set the pointer of the structure when serializing, for example with:

`src/serialization/data_ser.c`
```c
void cfe_gpsw_pub_key_ser(cfe_gpsw_pub_key *a, cfe_ser *buf) {
    CfeGpswPubKeySer msg = CFE_GPSW_PUB_KEY_SER__INIT;

    // t
    CfeVecG2Ser vec_g2;
    // serializing `vec_g2` here
    msg.t = &vec_g2; // <-- comment this line to make `_get_packed_size` succeed

    // y
    OctetSer y = OCTET_SER__INIT;
    cfe_FP12_BN254_pack(&(a->y), &y);
    msg.y = &y;

    size_t msg_len = cfe_gpsw_pub_key_ser__get_packed_size(&msg); // <-- segfault
   
   // ...
}
```
and extending the test suite with:

`test/serialization/data_ser.c`
```c
MunitResult test_gpsw_pub_key_ser(const MunitParameter *params, void *data) {
    cfe_ser buf;
    cfe_gpsw gpsw;
    cfe_gpsw_pub_key pk;
    cfe_vec sk;

    cfe_gpsw_init(&gpsw, 10);
    cfe_gpsw_master_keys_init(&pk, &sk, &gpsw);
    cfe_gpsw_generate_master_keys(&pk, &sk, &gpsw);

    cfe_gpsw_pub_key_ser(&pk, &buf);

    cfe_gpsw_free(&gpsw);
    cfe_vec_free(&sk);
    cfe_gpsw_pub_key_free(&pk);

    return MUNIT_OK;
}

MunitTest data_ser_tests[] = {
        {(char *) "/ec", test_ec_ser, NULL, NULL, MUNIT_TEST_OPTION_NONE, NULL},
        {(char *) "/mpz", test_mpz_ser, NULL, NULL, MUNIT_TEST_OPTION_NONE, NULL},
        {(char *) "/mat", test_mat_ser, NULL, NULL, MUNIT_TEST_OPTION_NONE, NULL},
        {(char *) "/msp", test_msp_ser, NULL, NULL, MUNIT_TEST_OPTION_NONE, NULL},
        {(char *) "/gpsw", test_gpsw_pub_key_ser, NULL, NULL, MUNIT_TEST_OPTION_NONE, NULL},
        {NULL, NULL,                                   NULL, NULL, MUNIT_TEST_OPTION_NONE, NULL}
};
```

Am I doing something wrong? Is the `vec_g2` protobuf definition lacks of something needed to be serialized correctly?
Thanks a lot!

**Comment by tilenmarc** [comment] 2020-12-11 08:13
Hi,
I would need to test your code, so I will look into it in the next days.

**Comment by ThibsG** [comment] 2020-12-11 08:24
Thanks a lot.
I guess the main problem is coming from `ECP2_BN254 *vec` because a pointer is not serializable as is, so we must convert this pointer into a single flat array (or `octet_ser`) with a manual processing for `ser` and `read`.

**Comment by ThibsG** [comment] 2020-12-12 09:50
If this can help, I came up with a working solution.
It flattens all the elements from `ECP2_BN254 *vec` pointer into an `octet_ser`.
Do you think this is a valid solution though?

`include/cifer/serialization/data.proto`:
```protobuf
message cfe_gpsw_pub_key_ser {
        required octet_ser t = 1;
        required octet_ser y = 2;
}
```
`src/serialization/data_ser.c`:
```c
void cfe_vec_G2_pack(cfe_vec_G2 *a, OctetSer *msg) {
    uint32_t ecp2_size = (4 * MODBYTES_256_56) * sizeof(char);
    msg->len = ecp2_size * a->size;
    msg->val = cfe_malloc(msg->len);
    msg->n_val = msg->len;
    msg->max = msg->len;
    for (size_t i = 0, j = 0; i < a->size; i++) {
        OctetSer chunk = OCTET_SER__INIT;
        cfe_ECP2_BN254_pack(&a->vec[i], &chunk);
        for (int k = 0; k < chunk.len; j++, k++) {
            msg->val[j] = chunk.val[k];
        }
    }
}

void cfe_vec_G2_unpack(cfe_vec_G2 *a, OctetSer *msg) {
    cfe_vec_G2_init(a, msg->n_val);

    size_t ecp2_size = (4 * MODBYTES_256_56) * sizeof(char);
    a->size = a->size / ecp2_size;

    for (size_t i = 0, j = 0; i < a->size; i++) {
        OctetSer chunk = OCTET_SER__INIT;
        chunk.val = cfe_malloc(ecp2_size);
        chunk.len = ecp2_size;
        for (size_t k = 0; k < ecp2_size; j++, k++) {
            chunk.val[k] = msg->val[j];
        }

        ECP2_BN254 ecp;
        cfe_ECP2_BN254_unpack(&ecp, &chunk);
        a->vec[i] = ecp;

        free(chunk.val);
    }
}

void cfe_gpsw_pub_key_ser(cfe_gpsw_pub_key *a, cfe_ser *buf) {
    CfeGpswPubKeySer msg = CFE_GPSW_PUB_KEY_SER__INIT;

    // cfe_vec_G2 t
    OctetSer t = OCTET_SER__INIT;
    cfe_vec_G2_pack(&(a->t), &t);
    msg.t = &t;

    // FP12_BN254 y
    OctetSer y = OCTET_SER__INIT;
    cfe_FP12_BN254_pack(&(a->y), &y);
    msg.y = &y;

    buf->len = cfe_gpsw_pub_key_ser__get_packed_size(&msg);
    buf->ser = cfe_malloc(buf->len);

    cfe_gpsw_pub_key_ser__pack(&msg, buf->ser);

    free(msg.y->val);
}

cfe_error cfe_gpsw_pub_key_read(cfe_gpsw_pub_key *a, cfe_ser *buf) {
    CfeGpswPubKeySer *msg;
    msg = cfe_gpsw_pub_key_ser__unpack(NULL, buf->len, buf->ser);
    if (msg == NULL) {
        return 1;
    }

    cfe_vec_G2_unpack(&(a->t), msg->t);
    cfe_FP12_BN254_unpack(&(a->y), msg->y);

    cfe_gpsw_pub_key_ser__free_unpacked(msg, NULL);
    return 0;
}
```

and the following test passes:
`test/serialization/data_ser.c`
```c
MunitResult test_gpsw_pub_key_ser(const MunitParameter *params, void *data) {
    cfe_ser buf;
    cfe_gpsw gpsw;
    cfe_gpsw_pub_key pk, pk2;
    cfe_vec sk;

    cfe_gpsw_init(&gpsw, 10);
    cfe_gpsw_master_keys_init(&pk, &sk, &gpsw);
    cfe_gpsw_generate_master_keys(&pk, &sk, &gpsw);

    cfe_gpsw_pub_key_ser(&pk, &buf);
    cfe_gpsw_pub_key_read(&pk2, &buf);

    munit_assert(pk.t.size == pk2.t.size);
    for (size_t i = 0; i < pk.t.size; i++) {
        int check = ECP2_BN254_equals(&pk.t.vec[i], &pk2.t.vec[i]);
        munit_assert(check == 1);
    }

    cfe_gpsw_free(&gpsw);
    cfe_vec_free(&sk);
    cfe_gpsw_pub_key_free(&pk);

    return MUNIT_OK;
}
```

**Comment by tilenmarc** [comment] 2020-12-14 13:56
Hi @ThibsG,
I prepared for you a serialization of `cfe_vec_G2` struct. It changes the struct into a vector of octets, and then serialize it. Check the `test_vec_octet_ser` test in https://github.com/tilenmarc/CiFEr/blob/marshalling/test/serialization/data_ser.c (in the latest commit) to see how to use it (and track beck the functions to see how I implemented it).
I assume you know how to use it to build a serialization of stucts in GPSW. Let me know if you succeeded. 
Best, Tilen

**Comment by ThibsG** [comment] 2020-12-14 17:51
Thanks a lot @tilenmarc, your solution works fine and seems more generic than mine.

What do you think about opening a PR about serialization (based on your branch) so I can share with you upcoming work (ie: serialization of `cfe_gpsw_pub_key` and so on)?

**Comment by tilenmarc** [comment] 2020-12-18 11:02
@ThibsG, that would be great! I have a long term vision of doing it for all the schemes, but starting with ABE schemes is a good start!

**Comment by ThibsG** [comment] 2020-12-22 09:48
Ok then, do you want to start opening the PR to merge your https://github.com/tilenmarc/CiFEr/tree/marshalling branch, and then I add my commits to it?
Or do you want to first merge `marshalling` branch into master,  then I open a second PR after I rebased?

**Comment by tilenmarc** [comment] 2020-12-23 09:19
I think you can simply pull my branch to your fork, add your stuff and open a PR with all. The problem is that I have to review my code, check for memory leaks, etc. before I merge. And in the next weeks I will not have time to do it. So don't wait for my PR, just build on top of my work.

**Comment by ThibsG** [comment] 2020-12-23 09:26
This is totally fine, there is no urgency at all :wink:
I will also be quite busy in coming weeks too, so we keep in touch

**Closed** 2021-02-08 14:57 UTC
